### ISSUE TITLE
Integration with AudioInput Cordova Plugin

### ISSUE THREAD

**Issue by asineath** [edimuj/speechcapture#2]
Do you have an example for using speechcapture.js with the Cordova plugin AudioInput? 
How are audioinput.start() and speechcapture.start() intended to interact?

**Comment by edimuj** [comment]
This library uses the cordova-audioinput-plugin if it is present. It basically wraps the audioinput plugin and adds the speech capture functionality. When using this lib, it is recommended that you don't use the audioinput plugin API directly; i.e. don't call the audioinput plugin API from your code; instead use the speechlibrary API to start, stop audioinput.

**Comment by edimuj** [comment]
Since there havent been any activity on this question for some time, I'm closing it.

**Comment by devikaramje** [comment]
I'm not able to make it work in cordova (ionic). Can we have an example? it's saying variable speechcapture is not found,

**Comment by devikaramje** [comment]
Okay it worked once I stopped linking the files and just merged speechcapture.js and speechcapture-demo.js into one file (weird because I linked them all correctly :/).
