### ISSUE TITLE
possible typo in the speechcapture.min.js file

### ISSUE THREAD

**Issue by albaspazio** [edimuj/speechcapture#3]
There Sirs

It seems that the min version contain a typo error, precisely here 

,SPEECH_DETECTION_MAX_LENGTH:500,SPEECH_DETECTION_MIN_LENGTH:1e4,

should it be the reverse : min            500, max 10000 ???
thanks in advance
Alberto

by the way....thank you very much also for the audioinput plugin, I hope to enjoy also this one....

**Comment by edimuj** [comment]
Thank you, I'll look into this and commit a new fixed version.
