### ISSUE TITLE
Visualization Real Time

### ISSUE THREAD

**Issue by devikaramje** [edimuj/speechcapture#5]
It's not possible to create analyser node for real time volume visualization? :(

**Comment by edimuj** [comment]
I'm sorry to hear that, could you please elaborate a little bit more on this?

**Comment by edimuj** [comment]
After I read your other issue, I think I understand a little better. As I wrote there, this library is built to detect and capture speech in cases where the voice data is to be sent to a server.

You're of course welcome to fork this project if you want to have a go at extending it with that type of specialized functionality.
